language: python

python:
  - "3.7"

install:
  - pip install -e .

jobs:
  include:
    - stage: black
      before_script: pip install black
      script: black osm2gtfs

    - stage: flake8
      before_script: pip install flake8
      script: flake8 osm2gtfs

    - stage: non regression test
      script: python -m unittest discover -p 'tests_*.py'
